### ISSUE TITLE
Channel names

### ISSUE THREAD

**Issue by Zook-coder** [Celiian/MetaTube#33]
After a research, the result may don't have any clones or identical names. 
So @Thomlam , can you check that at the creation of the channel ?

Best regards,
Zook

**Comment by Thomlam** [comment]
@Zook-coder  It's ok for me. 
I think @Celiian and @elimf are doing it tonight, if they don't I will.

Sincerely,
Thomlam

**Comment by N0ku** [comment]
Hey, if the problem is solved do not forget to close the issue guys,
@Thomlam are there still possible clones ? Good night 

Kind regards,
Lucie L
